-- Weather Observation Station 15
SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345);

-- Weather Observation Station 16
SELECT ROUND(MIN(LAT_N), 4)
FROM STATION
WHERE LAT_N > 38.7780;

-- Weather Observation Station 17
SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N = (SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.7780)

-- Weather Observation Station 18
SELECT ROUND(ABS(MAX(LAT_N)-MIN(LAT_N)) + ABS(MAX(LONG_W)-MIN(LONG_W)), 4)
FROM STATION

-- Weather Observation Station 19
SELECT
ROUND(SQRT((MIN(LAT_N)-MAX(LAT_N))*(MIN(LAT_N)-MAX(LAT_N)) + (MIN(LONG_W)-MAX(LONG_W))*(MIN(LONG_W)-MAX(LONG_W))), 4)
FROM STATION
