-- Weather Observation Station 15
SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345);

-- Weather Observation Station 16
SELECT ROUND(MIN(LAT_N), 4)
FROM STATION
WHERE LAT_N > 38.7780;

-- Weather Observation Station 17
SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N = (SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.7780)

-- Weather Observation Station 18
SELECT ROUND(ABS(MAX(LAT_N)-MIN(LAT_N)) + ABS(MAX(LONG_W)-MIN(LONG_W)), 4)
FROM STATION

-- Weather Observation Station 19
SELECT
ROUND(SQRT((MIN(LAT_N)-MAX(LAT_N))*(MIN(LAT_N)-MAX(LAT_N)) + (MIN(LONG_W)-MAX(LONG_W))*(MIN(LONG_W)-MAX(LONG_W))), 4)
FROM STATION

-- Weather Observation Station 20
WITH ORDERED AS(
    SELECT LAT_N, 
        ROW_NUMBER() OVER (ORDER BY LAT_N) AS RN,
        COUNT(*) OVER() AS TOTAL_ROWS
    FROM STATION
),
MIDDLE AS(
    SELECT LAT_N, RN, TOTAL_ROWS
    FROM ORDERED
    WHERE RN = FLOOR((TOTAL_ROWS + 1)/2)
        OR RN = CEIL((TOTAL_ROWS + 1)/2)
)
SELECT ROUND(AVG(LAT_N), 4) FROM MIDDLE
